[phases.setup]
nixPkgs = ['nodejs']

[phases.install]
cmds = ['npm ci --ignore-scripts']

[phases.build]
cmds = ['npx prisma generate', 'npm run build']

[start]
cmd = 'npx prisma migrate deploy && npm start'