[phases.setup]
nixPkgs = ['nodejs']

[phases.install]
cmds = [
  'rm -rf node_modules/.cache || true',
  'npm ci --ignore-scripts'
]

[phases.build]
cmds = ['npx prisma generate', 'npm run build']

[start]
cmd = 'npx prisma migrate deploy && npm start'